export const EXT_TO_LANG: Record<string, string> = {
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.ts': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.tsx': 'tsx',
  '.jsx': 'jsx',
  '.py': 'python',
  '.rb': 'ruby',
  '.rs': 'rust',
  '.go': 'go',
  '.java': 'java',
  '.kt': 'kotlin',
  '.swift': 'swift',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cs': 'csharp',
  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'zsh',
  '.fish': 'fish',
  '.sql': 'sql',
  '.json': 'json',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.xml': 'xml',
  '.html': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.lua': 'lua',
  '.r': 'r',
  '.R': 'r',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.hs': 'haskell',
  '.clj': 'clojure',
  '.scala': 'scala',
  '.php': 'php',
  '.pl': 'perl',
  '.dockerfile': 'dockerfile',
  '.tf': 'hcl',
  '.zig': 'zig',
  '.nim': 'nim',
  '.dart': 'dart',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.fs': 'fsharp',
  '.fsx': 'fsharp',
};

export const LANG_TO_EXT: Record<string, string> = (() => {
  const map: Record<string, string> = {};
  for (const [ext, lang] of Object.entries(EXT_TO_LANG)) {
    if (!(lang in map)) map[lang] = ext;
  }
  return map;
})();
