#!/usr/bin/env node
const core = require('mor-core').default;
const helpers = require('mor-cli-helpers');

const program = new helpers.Program({
  name: 'mor',
  prettyName: 'Troll Mother 💕  nurses your monorepo'
});

core.config().then(config => {
  program
  .command('bootstrap', 'yarn', ['bootstrap'], { cwd: config.rootPath })
  .command('flow', 'flow', { cwd: config.rootPath }) // <rootPath>/node_modules/.bin/flow
  .command('lerna', 'lerna', { cwd: config.rootPath }) // <rootPath>/node_modules/.bin/lerna
  .command('ls', 'mor-ls', { cwd: __dirname }) // ./node_modules/.bin/mor-ls
  .command('npm', 'npm', { cwd: config.rootPath })
  .command('prettier-all', './prettier-all', { cwd: __dirname }) // ./prettier-all
  .command('record', './record', { cwd: __dirname })
  .command('root', 'mor-root', { cwd: __dirname }) // ./node_modules/.bin/mor-root
  .command('t', 'mor-test', { cwd: __dirname }) // ./node_modules/.bin/mor-test
  .command('test', 'mor-test', { cwd: __dirname }) // ./node_modules/.bin/mor-test
  .command('watch' , 'nurture', { cwd: config.rootPath })
  .command('yarn', 'yarn', { cwd: config.rootPath })
  .parse(process.argv);
});
