#!/usr/bin/env node
const core = require('mor-core').default;
const helpers = require('mor-helper-cli');

const program = new helpers.Program({
  name: 'mor',
  prettyName: 'Troll Mother 💕  nurses your monorepo'
});

core.config().then(config => {
  program
  .command('bootstrap', 'yarn', ['bootstrap'], { cwd: config.rootPath })
  .command('flow', 'flow', { cwd: config.rootPath }) // <rootPath>/node_modules/.bin/flow
  .command('ls', 'mor-ls', { cwd: __dirname }) // ./node_modules/.bin/mor-ls
  .command('test', 'mor-test', { cwd: __dirname }) // ./node_modules/.bin/mor-test
  .command('watch' , 'nurture', { cwd: config.rootPath })
  .command('record-demo', './record-demo', { cwd: __dirname })
  .command('prettier-all', './prettier-all', { cwd: __dirname }) // ./prettier-all
  .parse(process.argv);
});
